@startuml
Inscripcion --> Alumno
Inscripcion --> Materia

Materia -> Materia
Alumno -> Materia

class Alumno {
boolean aproboCorrelativasDe(Materia)
}

class Materia {

}

class Inscripcion {
boolean aprobada()
}
@enduml